# build project
FROM node:18.14.2-alpine3.17
WORKDIR /app
COPY ["package*.json", "."]
RUN npm install --only=production
COPY [".", "."]
RUN npm run build


# create nginx server
FROM nginx:1.23.3-alpine
COPY --from=0 ["/app/build", "/usr/share/nginx/html/todoReact"]
COPY ["./nginx.conf", "/etc/nginx/nginx.conf"]
EXPOSE 80
